# repo branches

branches:
  only:
  - master

# job environment

dist: xenial

services:
  - xvfb

addons:
  firefox: latest

sudo: false

language: python

python:
  - "3.5"
  - "3.6"

# job phases

install:
  - pip install --editable .[test]

script:
  - pytest -m "not browser" --cov --cov-report=term-missing

after_success:
  - coveralls
  - xvfb-run make test ; pytest -m "browser" ; pkill gunicorn
