# repo branches

branches:
  only:
  - master

# job environment

dist: xenial

services:
  - xvfb

addons:
  firefox: latest

sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# job phases

install:
  - pip install --editable .[test]

script:
  - pytest -v -m "not browser" --cov --cov-report=term-missing

after_success:
  - coveralls
  - chmod +x ./run-browser-tests-in-travis.sh ; ./run-browser-tests-in-travis.sh
